In [1]:
import numpy as np

# super -> (x,0,0)
# super with brackets -> (x,1,0)
# sub -> (x,0,1)
# sub with brackets -> (x,1,1)

def getscrpt(x,flag,subs=0):
    if(type(x)==int):
        x = str(x)
    normal = "t0123456789+-=()"
    super_s = "ᵗ⁰¹²³⁴⁵⁶⁷⁸⁹⁺⁻⁼⁽⁾"
    sub_s = "ₜ₀₁₂₃₄₅₆₇₈₉₊₋₌₍₎"
    if subs==1:
        res = x.maketrans(''.join(normal), ''.join(sub_s))
    else:
        res = x.maketrans(''.join(normal), ''.join(super_s))
    if flag==1:
        if subs==1:
            return "₍"+x.translate(res)+"₎"
        else:
            return "⁽"+x.translate(res)+"⁾"
    else:
        return x.translate(res) 

### Input A, m ,V[0]

In [2]:
A=np.array([[1,2,3,4],
            [2,3,4,5],
            [3,4,5,6],
            [4,5,6,7]])

m=3

V=np.zeros(shape=(m+1,A.shape[0]))
V[0]=np.array([1,0,0,0])

H=np.zeros(shape=(m+1,m))
V[0]=V[0]/np.linalg.norm(V[0])

In [3]:
for k in range(1,m+1):
    print("Step {}: Generating Vector {} & Volumn {} of Hessenberg Matrix \n".format(k,k+1,k))
    
    temp=V[k-1].reshape(V[k-1].shape[0],1)
    v_cap=np.matmul(A,temp)
    print("Vcap = AV{}={}{}\n".format(getscrpt(k,0,1),v_cap.T[0],getscrpt("t",0,0)))
    
    print("(Printing Column {} of Hessenberg) \n".format(k))
    for j in range(1,k+1):        
        H[j-1][k-1]=np.dot(V[j-1],v_cap)
        print("H{}{} = {:.4f}\n".format(getscrpt(j,0,1),getscrpt(k,0,1),H[j-1][k-1]))
        temp2=V[j-1].reshape(V[j-1].shape[0],1)
        v_cap=np.subtract(v_cap,H[j-1][k-1]*temp2)
        print("Vcap = Vcap - H{}{}V{} = {}{} \n".format(getscrpt(j,0,1),getscrpt(k,0,1),getscrpt(j,0,1),v_cap.T[0],getscrpt("t",0,0)))
        
    H[k+1-1][k-1]=np.linalg.norm(v_cap)
    print("H{}{} = {:.4f} \n".format(getscrpt(k+1,0,1),getscrpt(k,0,1),H[k+1-1][k-1]))
    
    if(H[k+1-1][k-1]==0):
        break
    print("(Printing Vector {}) \n".format(k+1))
    np.set_printoptions(formatter={'float_kind':'{:f}'.format})
    V[k]=list(v_cap/H[k][k-1])
    print("V{} = {} \n".format(getscrpt(k+1,0,1),V[k]))
    print("--------------------------------------------------")

Step 1: Generating Vector 2 & Volumn 1 of Hessenberg Matrix 

Vcap = AV₁=[1. 2. 3. 4.]ᵗ

(Printing Column 1 of Hessenberg) 

H₁₁ = 1.0000

Vcap = Vcap - H₁₁V₁ = [0. 2. 3. 4.]ᵗ 

H₂₁ = 5.3852 

(Printing Vector 2) 

V₂ = [0.000000 0.371391 0.557086 0.742781] 

--------------------------------------------------
Step 2: Generating Vector 3 & Volumn 2 of Hessenberg Matrix 

Vcap = AV₂=[5.385165 7.056423 8.727681 10.398939]ᵗ

(Printing Column 2 of Hessenberg) 

H₁₂ = 5.3852

Vcap = Vcap - H₁₂V₁ = [0.000000 7.056423 8.727681 10.398939]ᵗ 

H₂₂ = 15.2069

Vcap = Vcap - H₂₂V₂ = [0.000000 1.408723 0.256132 -0.896460]ᵗ 

H₃₂ = 1.6893 

(Printing Vector 3) 

V₃ = [0.000000 0.833908 0.151620 -0.530669] 

--------------------------------------------------
Step 3: Generating Vector 4 & Volumn 3 of Hessenberg Matrix 

Vcap = AV₃=[0.000000 0.454859 0.909718 1.364576]ᵗ

(Printing Column 3 of Hessenberg) 

H₁₃ = 0.0000

Vcap = Vcap - H₁₃V₁ = [0.000000 0.454859 0.909718 1.364576]ᵗ 

H₂₃ = 1.6893

Vcap = V

In [4]:
print(V.T)

[[1.000000 0.000000 0.000000 0.000000]
 [0.000000 0.371391 0.833908 0.654678]
 [0.000000 0.557086 0.151620 -0.133911]
 [0.000000 0.742781 -0.530669 0.743952]]


In [5]:
print(H)

[[1.000000 5.385165 0.000000]
 [5.385165 15.206897 1.689303]
 [0.000000 1.689303 -0.206897]
 [0.000000 0.000000 0.000000]]
