In [1]:
from numpy import linalg as LA
import numpy as np



def getscrpt(x,flag,subs=0):
    if(type(x)==int):
        x = str(x)
    normal = "t0123456789+-=()"
    super_s = "ᵗ⁰¹²³⁴⁵⁶⁷⁸⁹⁺⁻⁼⁽⁾"
    sub_s = "ₜ₀₁₂₃₄₅₆₇₈₉₊₋₌₍₎"
    if subs==1:
        res = x.maketrans(''.join(normal), ''.join(sub_s))
    else:
        res = x.maketrans(''.join(normal), ''.join(super_s))
    if flag==1:
        if subs==1:
            return "₍"+x.translate(res)+"₎"
        else:
            return "⁽"+x.translate(res)+"⁾"
    else:
        return x.translate(res) 

# 1. Input

In [2]:
A = np.array([
    [1, 3, 4],
    [3, 2, -1],
    [4, -1, 1]
])


In [3]:


s = np.sqrt(A[0][1]**2 + A[0][2]**2)
print(f"S: {s}")

x2 = np.sqrt(1/2 * (1 + A[0][1]/s))
print(f"\nx2: {x2}")

x3 = A[0][2] / (2*x2*s)
print(f"\nx3: {x3}")

v1 = np.array([[0], [x2], [x3]])
print(f"\nv1: \n{v1}")

T1 = np.identity(3) - 2*np.matmul(v1,v1.T)
print(f"\nT1: \n{T1}")

T = np.around(np.matmul(np.matmul(T1,A), T1), decimals=2)
print(f"\nTridiagonal form(T): \n\n{T}")



print("-------------------------------------------------------------------------------------------")





print("\n\nDefine T1 and T2 from T\n k is 2\n")
k = 2

bk = T[k-1, k]
print(f"\nbk = {T[k-1, k]}\n")

T1 = T[:k, :k].copy()
T1[-1, 1] = T1[-1, -1] - T[k-1, k]
print(f"T1: \n{T1}\n")

T2 = T[k:, k:].copy()
T2[0,0] = T2[0,0] - T[k-1, k]
print(f"T2: \n{T2}\n")



print("Since T1 and T2 are symmetric tridiagonal. we can find orthogonal matrices Q1 and Q2 \nsuch that T1 = Q1D1Q1{} and T2 = Q2D2Q2{}".format(getscrpt("t",0), getscrpt("t",0)))
D1, Q1 = np.linalg.eig(T1)
D1 = np.diag(D1)

print(f"\nD1: \t\n{D1}\n")
print(f"Q1: \n{Q1}\n\n")
print("Q1{}: \n{}\n\n".format(getscrpt("t",0), Q1.T))


D2, Q2 = np.linalg.eig(T2)
D2 = np.diag(D2)

print(f"D2: \n{D2}\n")
print(f"Q2: \n{Q2}\n")
print("Q2{}: \n{}\n\n".format(getscrpt("t",0), Q2.T))



v = np.zeros((len(T),1))

for i in range(len(v)):
    if i == k or i == k-1:
        v[i] = 1


print(f"v: \n{v}\n")
def merge_diagonal(T1, T2):
    row = len(T1) + len(T2)
    col = len(T1[0]) + len(T2[0])

    merged = np.zeros((row, col))
    for i in range(len(T1)):
        for j in range(len(T1[0])):
            merged[i][j] = T1[i][j]
        
    for i in range(len(T1), len(T1) + len(T2)):
        for j in range(len(T1[0]), len(T1[0]) + len(T2[0])):

            merged[i][j] = T2[i - len(T1)][j - len(T1[0])] 
            
    return merged





Q_diag = merge_diagonal(Q1, Q2)
print(f"\nQ Diagonal: ")

print(f"{Q_diag}\n")




D_diag = merge_diagonal(D1, D2)
print(f"D Diagonal: \n{D_diag}\n\n")
Q_T_diag = merge_diagonal(Q1.T, Q2.T)
print(f"Q.T Diagonal: \n{Q_T_diag}\n\n")
u = np.dot(Q_T_diag, v)

print(f"u: \n{u}\n")
D_hat = D_diag + bk*np.dot(u,u.T)
print(f"D_hat: \n{D_hat}\n")



eig_val, eig_vec = np.linalg.eig(D_hat)

print(f"Eigen values and corresponding Eigen Vectors of D_hat are:\n")


for i in range(len(D_hat)):
    print(f"lambda_{i+1}: {eig_val[i]}")
    print(f"q_{i+1}: {eig_vec.T[i]}")
    print("\n\n")



I = np.identity(len(D_hat))
l = eig_val[0]
proof1 = np.round(1 + bk * np.dot( np.dot(u.T, np.linalg.inv(D_diag - l*I)), u), decimals = 3)

proof2 = np.dot(np.linalg.inv(D_diag - l*I),u)
proof2_n = proof2/LA.norm(proof2)



S: 5.0

x2: 0.8944271909999159

x3: 0.4472135954999579

v1: 
[[0.        ]
 [0.89442719]
 [0.4472136 ]]

T1: 
[[ 1.   0.   0. ]
 [ 0.  -0.6 -0.8]
 [ 0.  -0.8  0.6]]

Tridiagonal form(T): 

[[ 1.  -5.   0. ]
 [-5.   0.4  0.2]
 [ 0.   0.2  2.6]]
-------------------------------------------------------------------------------------------


Define T1 and T2 from T
 k is 2


bk = 0.2

T1: 
[[ 1.  -5. ]
 [-5.   0.2]]

T2: 
[[2.4]]

Since T1 and T2 are symmetric tridiagonal. we can find orthogonal matrices Q1 and Q2 
such that T1 = Q1D1Q1ᵗ and T2 = Q2D2Q2ᵗ

D1: 	
[[ 5.61597448  0.        ]
 [ 0.         -4.41597448]]

Q1: 
[[ 0.73476024  0.6783269 ]
 [-0.6783269   0.73476024]]


Q1ᵗ: 
[[ 0.73476024 -0.6783269 ]
 [ 0.6783269   0.73476024]]


D2: 
[[2.4]]

Q2: 
[[1.]]

Q2ᵗ: 
[[1.]]


v: 
[[0.]
 [1.]
 [1.]]


Q Diagonal: 
[[ 0.73476024  0.6783269   0.        ]
 [-0.6783269   0.73476024  0.        ]
 [ 0.          0.          1.        ]]

D Diagonal: 
[[ 5.61597448  0.          0.        ]
 [ 0. 

In [4]:
print(f"To validate the answers\nWrite below equation and put values, lambda = {eig_val[0]}")

To validate the answers
Write below equation and put values, lambda = 5.715031957585767



$1 + b_ku^T(D - \lambda I)^{-1} u .......eq1$


In [5]:
if proof1==0:
    print("After putting values, write the equation = zero(0) and L.H.S. = R.H.S")

After putting values, write the equation = zero(0) and L.H.S. = R.H.S


In [6]:
print(f"Write below equation and put values, lambda = {eig_val[0]}")

Write below equation and put values, lambda = 5.715031957585767


$(D - \lambda I)^{-1}...........eq2$

In [7]:
print(f"After putting values, write the equation = \n{proof2}, \n\nafter normalizing = \n{proof2_n} \n= q_1\n\nL.H.S = R.H.S")

After putting values, write the equation = 
[[ 6.84781131]
 [-0.07252589]
 [-0.30165622]], 

after normalizing = 
[[ 0.99897523]
 [-0.01058025]
 [-0.04400634]] 
= q_1

L.H.S = R.H.S
