### Inputs

In [ ]:
import numpy as np

# super -> (x,0,0)
# super with brackets -> (x,1,0)
# sub -> (x,0,1)
# sub with brackets -> (x,1,1)

def getscrpt(x,flag,subs=0):
    if(type(x)==int):
        x = str(x)
    normal = "t0123456789+-=()"
    super_s = "ᵗ⁰¹²³⁴⁵⁶⁷⁸⁹⁺⁻⁼⁽⁾"
    sub_s = "ₜ₀₁₂₃₄₅₆₇₈₉₊₋₌₍₎"
    if subs==1:
        res = x.maketrans(''.join(normal), ''.join(sub_s))
    else:
        res = x.maketrans(''.join(normal), ''.join(super_s))
    if flag==1:
        if subs==1:
            return "₍"+x.translate(res)+"₎"
        else:
            return "⁽"+x.translate(res)+"⁾"
    else:
        return x.translate(res) 

In [ ]:
A = np.array([[1,2,3,4],
             [4,5,6,7],
             [2,1,5,0],
             [4,2,1,0]])

# ITERATION 1

In [ ]:
# Edit d & e here
d = np.array([[4],[2],[4]]) 
e = np.array([[1],[0],[0]])
# ---------------------------------------

Beta = -1 * np.linalg.norm(d,2)
print("Beta = -||d||{} = {}".format(getscrpt(2,0,1),Beta))

dBe = d-Beta*e
print("d-Be{} = {}{}".format(getscrpt(1,1,0),np.transpose(dBe)[0],getscrpt("t",0,0)))

dBeNorm = np.linalg.norm(dBe,2)
print("||d-Be{}||{} = {:.5f}".format(getscrpt(1,1,0),getscrpt(2,0,1),dBeNorm))

Alpha = 1.414/dBeNorm
print("Alpha = {:.5f}".format(Alpha))

v = Alpha*dBe
print("v = Alpha*[d-Be{}] = {}{}".format(getscrpt(1,1,0),np.transpose(v)[0],getscrpt("t",0,0)))

vvt = np.dot(v,np.transpose(v))
I = np.identity(vvt.shape[0])
U = I-vvt
print("\nvv*=",vvt)
print("\nU =",U)

U = np.pad(U,((1, 0), (1, 0)))
U[0][0]=1
print("\nPadded U =",U)

H1 = np.dot(U,np.dot(A,U))
np.set_printoptions(formatter={'float_kind':'{:f}'.format})
print("\nH{} = UAU* = {}".format(getscrpt(1,0,1),H1))        

Beta = -||d||₂ = -6.0
d-Be⁽¹⁾ = [10.  2.  4.]ᵗ
||d-Be⁽¹⁾||₂ = 10.95445
Alpha = 0.12908
v = Alpha*[d-Be⁽¹⁾] = [1.29079949 0.2581599  0.5163198 ]ᵗ

vv*= [[1.66616333 0.33323267 0.66646533]
 [0.33323267 0.06664653 0.13329307]
 [0.66646533 0.13329307 0.26658613]]

U = [[-0.66616333 -0.33323267 -0.66646533]
 [-0.33323267  0.93335347 -0.13329307]
 [-0.66646533 -0.13329307  0.73341387]]

Padded U = [[ 1.          0.          0.          0.        ]
 [ 0.         -0.66616333 -0.33323267 -0.66646533]
 [ 0.         -0.33323267  0.93335347 -0.13329307]
 [ 0.         -0.66646533 -0.13329307  0.73341387]]

H₁ = UAU* = [[1.000000 -4.997886 1.600423 1.200846]
 [-5.996980 8.545861 -3.621041 0.753993]
 [0.000604 1.375939 3.009145 -1.382494]
 [0.001208 5.750973 -2.381890 -1.565351]]


# ITERATION 2

In [ ]:
# Edit d & e here
d = np.array([[1.379],[5.759]])
e = np.array([[1],[0]])
# ---------------------------------------

Beta = -1 * np.linalg.norm(d,2)
print("Beta = -||d||{} = {}".format(getscrpt(2,0,1),Beta))

dBe = d-Beta*e
print("d-Be{} = {}{}".format(getscrpt(1,1,0),np.transpose(dBe)[0],getscrpt("t",0,0)))

dBeNorm = np.linalg.norm(dBe,2)
print("||d-Be{}||{} = {:.5f}".format(getscrpt(1,1,0),getscrpt(2,0,1),dBeNorm))

Alpha = 1.414/dBeNorm
print("Alpha = {:.5f}".format(Alpha))

v = Alpha*dBe
print("v = Alpha*[d-Be{}] = {}{}".format(getscrpt(1,1,0),np.transpose(v)[0],getscrpt("t",0,0)))

vvt = np.dot(v,np.transpose(v))
I = np.identity(vvt.shape[0])
U = I-vvt
print("\nvv*=",vvt)
print("\nU =",U)
U = np.pad(U,((2, 0), (2, 0)))

# Uncomment below for a 3x3 A
# U = np.pad(U,((1, 0), (1, 0)))

U[0][0]=1
print("\nPadded U =",U)

from scipy.linalg import hessenberg
H, Q = hessenberg(A, calc_q=True)
print("\nH{} = UH{}U* = {}".format(getscrpt(2,0,1),getscrpt(1,0,1),H))

Beta = -||d||₂ = -5.9218005707723735
d-Be⁽¹⁾ = [7.300801 5.759000]ᵗ
||d-Be⁽¹⁾||₂ = 9.29880
Alpha = 0.15206
v = Alpha*[d-Be⁽¹⁾] = [1.110178 0.875728]ᵗ

vv*= [[1.232496 0.972215]
 [0.972215 0.766900]]

U = [[-0.232496 -0.972215]
 [-0.972215 0.233100]]

Padded U = [[1.000000 0.000000 0.000000 0.000000]
 [0.000000 0.000000 0.000000 0.000000]
 [0.000000 0.000000 -0.232496 -0.972215]
 [0.000000 0.000000 -0.972215 0.233100]]

H₂ = UH₁U* = [[1.000000 -5.000000 -1.539516 -1.276672]
 [-6.000000 8.555556 0.108475 3.698593]
 [0.000000 -5.918166 -2.168879 -1.142756]
 [0.000000 0.000000 -0.142756 3.613324]]
