In [1]:
import numpy as np

# super -> (x,0,0)
# super with brackets -> (x,1,0)
# sub -> (x,0,1)
# sub with brackets -> (x,1,1)

def getscrpt(x,flag,subs=0):
    if(type(x)==int):
        x = str(x)
    normal = "t0123456789+-=()"
    super_s = "ᵗ⁰¹²³⁴⁵⁶⁷⁸⁹⁺⁻⁼⁽⁾"
    sub_s = "ₜ₀₁₂₃₄₅₆₇₈₉₊₋₌₍₎"
    if subs==1:
        res = x.maketrans(''.join(normal), ''.join(sub_s))
    else:
        res = x.maketrans(''.join(normal), ''.join(super_s))
    if flag==1:
        if subs==1:
            return "₍"+x.translate(res)+"₎"
        else:
            return "⁽"+x.translate(res)+"⁾"
    else:
        return x.translate(res) 

In [2]:
A = np.array([[1,1,1],
             [2,0,0],
             [0,2,0],
             [0,0,2]])

b = np.array([[1],[0],[0],[0]])

In [3]:
AtA = np.dot(np.transpose(A),A)
print("A{}.A= \n {}".format(getscrpt("t",0,0),AtA))

Aᵗ.A= 
 [[5 1 1]
 [1 5 1]
 [1 1 5]]


In [4]:
Atb = np.dot(np.transpose(A),b)
print("A{}.b={}{}".format(getscrpt("t",0,0),np.transpose(Atb),getscrpt("t",0,0)))

Aᵗ.b=[[1 1 1]]ᵗ


In [5]:
print("Solve Aᵗ.A.X* = Aᵗ.b using any linear equation method like Gauss-Siedel,Cholesky etc.,")

Solve Aᵗ.A.X* = Aᵗ.b using any linear equation method like Gauss-Siedel,Cholesky etc.,


https://atozmath.com/CONM/GaussEli.aspx?q=GJ2

In [6]:
print("Final X* = {}{}".format(np.transpose(np.linalg.solve(AtA,Atb)),getscrpt("t",0,0)))

Final X* = [[0.14285714 0.14285714 0.14285714]]ᵗ
