In [1]:
import numpy as np

# super -> (x,0,0)
# super with brackets -> (x,1,0)
# sub -> (x,0,1)
# sub with brackets -> (x,1,1)

def getscrpt(x,flag,subs=0):
    if(type(x)==int):
        x = str(x)
    normal = "t0123456789+-=()"
    super_s = "ᵗ⁰¹²³⁴⁵⁶⁷⁸⁹⁺⁻⁼⁽⁾"
    sub_s = "ₜ₀₁₂₃₄₅₆₇₈₉₊₋₌₍₎"
    if subs==1:
        res = x.maketrans(''.join(normal), ''.join(sub_s))
    else:
        res = x.maketrans(''.join(normal), ''.join(super_s))
    if flag==1:
        if subs==1:
            return "₍"+x.translate(res)+"₎"
        else:
            return "⁽"+x.translate(res)+"⁾"
    else:
        return x.translate(res) 

### 1.Input Matrix B

In [2]:
B = np.array([[0.9,-0.2,-0.3],
              [0.1,1.0,-0.1],
              [0.3,0.2,1.1]])

### 2.A = I-B

In [3]:
I = np.identity(B.shape[0])

In [4]:
A = I-B
print("A=\n",A)

A=
 [[ 0.1  0.2  0.3]
 [-0.1  0.   0.1]
 [-0.3 -0.2 -0.1]]


### 3.Finding inf-Norm(A)< 1 implies the (absolute) convergence of the above series, and inf-Norm(A)> 1 implies that the series does not converge.

In [5]:
infA = np.linalg.norm(A,np.inf)
print("infA = {0:0.1f}, thus Neumann Series will converge.".format(infA))

infA = 0.6, thus Neumann Series will converge.


### 4. Iterations

In [6]:
Anew = np.identity(A.shape[0])
print("for k=0")
print(Anew)
for i in range(1,6):
    Anew = np.linalg.matrix_power(A,i) + Anew
    print("\nfor k={0}".format(i))
    print(Anew)

for k=0
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]

for k=1
[[ 1.1  0.2  0.3]
 [-0.1  1.   0.1]
 [-0.3 -0.2  0.9]]

for k=2
[[ 1.    0.16  0.32]
 [-0.14  0.96  0.06]
 [-0.28 -0.24  0.8 ]]

for k=3
[[ 0.988  0.136  0.284]
 [-0.128  0.96   0.048]
 [-0.244 -0.216  0.812]]

for k=4
[[ 1.      0.1408  0.2816]
 [-0.1232  0.9648  0.0528]
 [-0.2464 -0.2112  0.824 ]]

for k=5
[[ 1.00144  0.14368  0.28592]
 [-0.12464  0.9648   0.05424]
 [-0.25072 -0.21408  0.82256]]


### 5. Do the iterations till k=n is similar to actual inverse(B)

In [7]:
print("B{}{} =\n{}".format(getscrpt('-',0,0),getscrpt(1,0,0),np.linalg.inv(B)))

B⁻¹ =
[[ 1.          0.14285714  0.28571429]
 [-0.125       0.96428571  0.05357143]
 [-0.25       -0.21428571  0.82142857]]
